name: Deploy AWS Resources in Terraform
run-name: ${{ github.actor }} deployed the Terraform code to AWS.
on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
      TF_VAR_private_subnets: ${{ secrets.PRIVATE_SUBNETS }}
      TF_VAR_public_subnets: ${{ secrets.PUBLIC_SUBNETS }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: hashicorp/setup-terraform@v2
      - uses: actions/checkout@v3

      - name: print runner info
        run: echo "OS=${{ runner.os }} BRANCH=${{ github.ref }} REPO=${{ github.repository }}"

      - name: format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: initialize
        id: init
        run: terraform init

      - name: validate
        id: validate
        run: terraform validate
        
      - name: plan
        id: plan
        run: terraform plan

  docs:
    on:
      - pull_request
    jobs:
      docs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"